### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by moshpirit** [czlee/debatekeeper#33]
So, I made this icon, which I think it goes much better with the current design of the app since it uses the Google Material Design notification icon as a bell and not the one drawn in the current logo.

Of course this is just a suggestion and I still keep the SVG file in case you want me to change anything.

![My proposal](https://i.imgur.com/6VIgXgC.png)

**Comment by moshpirit** [comment]
UPDATE (see https://github.com/czlee/debatekeeper/pull/31)

![](https://i.imgur.com/ZUFLY9s.png)

**Comment by czlee** [comment]
Merged this in b9d19e666d6d7beb85c383ec83df88bf53d9a1cb, hope that's still okay, thanks!
