### ISSUE TITLE
Document bell sound "metrics" to aid future replacement

### ISSUE THREAD

**Issue by res2k** [czlee/debatekeeper#49]
The currently used bell sound was obtained from a commercial source with probably restricted usage rights.
Contributors and/or forkers may want to use a sound that is licensed liberally (e.g. from https://freesound.org/, a repository of Creative Commons licensed sounds), or just _some_ sound file.

Either way, in order to pick or create suitable sound files, it would be helpful to know some important "metrics":
* Length of bell sound and/or sound file
* Interval between bells for "2x, 3x" copies

I suggest to add these to the README part where the bell sound provision is discussed.

**Comment by czlee** [comment]
Great suggestion, thanks 🙂
